#! /bin/sh

set -e

case "$1" in
start)
    echo -n "Starting helloworld daemon: "
     	  if [ -x /data/simcom_demo ]
	  then
	  start-stop-daemon -S -b -a /data/simcom_demo
	  else
	  cp -f /usr/bin/simcom_demo /data/simcom_demo
	  start-stop-daemon -S -b -a /data/simcom_demo
	  fi
    echo "done"
    ;;
  stop)
    echo -n "Stopping simcom_demo: "
     start-stop-daemon -K -n simcom_demo
    echo "done"
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage simcom_demo { start | stop | restart }" >&2
    exit 1
    ;;
esac

exit 0
